### ISSUE TITLE
Causes game crash when Vanilla Turrets are placed/exist in the world.

### ISSUE THREAD

**Issue by Kiithnaras** [viktor-ferenczi/performance-improvements#18] opened 2022-03-22 06:31 UTC
After an hour of troubleshooting, mod-shuffling, and testing, I've come to the conclusion that this plugin's recent update causes the game to crash on world load if any vanilla turrets exist at all in the world and are powered on (enabling their targeting systems).

Example Crash Log trace:
```

2022-03-22 02:29:11.163 - Thread:   1 ->  Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Weapons.MyLargeTurretTargetingSystem.UpdateVisibilityCacheCounters()
   at Sandbox.Game.Weapons.MyLargeTurretBase.DoUpdateTimerTick()
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.OnTimerTick(MyEntityComponentContainer obj)
   at System.DelegateExtensions.InvokeIfNotNull[T1](Action`1 handler, T1 arg1)
   at Sandbox.Game.Components.MyTimerComponent.Update(Boolean forceUpdate)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.UpdateAfterSimulation10()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation10()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2022-03-22 02:29:11.163 - Thread:   1 ->  Showing message
2022-03-22 02:29:12.011 - Thread:   1 ->  
================================== CRASH INFO ==================================
AppVersion: 01_200_032
GameName: Space Engineers
IsOutOfMemory: False
IsGPU: False
IsNative: False
IsTask: False
IsExperimental: True
ProcessRunTime: 77
PCUCount: 5873
IsHang: False
GCMemory: 1737
GCMemoryAllocated: 1737
HWAvailableMemory: 16415
ProcessPrivateMemory: 8226
AnalyticId: SE
================================== OFNI HSARC ==================================
```

**Comment by Kiithnaras** [comment] 2022-03-22 06:42
The crashes do not occur when the Targeting Allocation optimization option is disabled.

**Comment by dorimanx** [comment] 2022-03-22 16:55
This type of crash was there before, it's keen code issue, at server side turret is already destroyed, but as client side it's not!
so client send update turret to server, but server has no turret! and client crash!

This will be the same if you disable the optimization and player for some time shooting and grinding active turrets.

**Comment by viktor-ferenczi** [comment] 2022-03-22 17:55
The crash in the description was caused by a crash during plugin initialization, which left a collection variable uninitialized.
```
2022-03-21 20:25:46.778 - Thread:   1 ->  Critical: PerformanceImprovements: Update failed
[NullReferenceException] Object reference not set to an instance of an object.
Method: Void Clean()
Traceback:
   at Shared.Patches.MyLargeTurretTargetingSystemPatch.Clean()
   at Shared.Patches.PatchHelpers.PatchUpdates()
   at ClientPlugin.Plugin.Update()
```
It was fixed in 1.7.1 shortly after the 1.7.0 release.

**Comment by viktor-ferenczi** [comment] 2022-03-22 21:01
This issue was reported by two players already. I could not reproduce the issue, despite I got a test world and blueprint. The other player showed me it crashing via a screen share.

The problem is there. Looks like a race condition, which happens randomly, depending on the timing.

A speculative fix will follow in 1.7.3 which you can test.

**Comment by viktor-ferenczi** [comment] 2022-03-22 21:56
`UpdateVisibilityCacheCounters` must not be called at all if the targeting system fix is enabled. The only place it is called from is `UpdateVisibilityCache`, which the plugin completely replaces with a prefix patch. How that's still called is unclear. Switching over the patch to `UpdateVisibilityCacheCounters` to see what happens.

**Comment by viktor-ferenczi** [comment] 2022-03-27 13:16
No crashes reported since 1.7.3

**Closed by viktor-ferenczi** 2022-03-27 13:16 UTC
