### ISSUE TITLE
Detected conflicting code since last update

### ISSUE THREAD

**Issue by Sardaukai** [viktor-ferenczi/performance-improvements#61] opened 2024-05-20 18:30 UTC
I am not able to tell more about it but I get this error log when starting torch server.
Server seems to run normally.

20:27:28.4104 [FATAL]  PerformanceImprovements: Detected conflicting code changes:
20:27:28.4104 [INFO]   PerformanceImprovements: Code change in VRageMath.MatrixI Sandbox.Game.Entities.MyCubeGrid::PasteBlocksServer(System.Collections.Generic.List`1<VRage.Game.MyObjectBuilder_CubeGrid> gridsToMerge); expected abb0d7f4, actual e7010d51
20:27:28.4104 [INFO]   PerformanceImprovements: Code change in VRageMath.MatrixI Sandbox.Game.Entities.MyCubeGrid::PasteBlocksServer(System.Collections.Generic.List`1<VRage.Game.MyObjectBuilder_CubeGrid> gridsToMerge); expected abb0d7f4, actual e7010d51

**Comment by viktor-ferenczi** [comment] 2024-05-21 22:30
Duplicate of #60

**Comment by viktor-ferenczi** [comment] 2024-05-24 15:29
In my local testing the code hash is `abb0d7f4`.

I guess something is patching the same method earlier than this plugin, so the code appears to be different.

I can whitelist this case once it is tested. Please send me the list of plugins you use and their load order or the relevant log lines which gives me this information.

**Comment by viktor-ferenczi** [comment] 2024-05-24 19:41
In `PerformanceImprovements.cfg` change `DetectCodeChanges` to `false`, it will disable the code hash verification.

Alternatively set this environment variable to disable the code verification:
`SE_PLUGIN_DISABLE_METHOD_VERIFICATION=1`

These are documented in ⁠the `#troubleshooting` channel on the SE Mods Discord.

**Closed** 2024-05-30 20:11 UTC
